### ISSUE TITLE
Trireme with weave Net

### ISSUE THREAD

**Issue by rchunduru** [aporeto-inc/trireme#122]
From the documentation, Trireme works with Flannel. Does it work with Weave Net?

**Comment by Dogild** [comment]
Hi @rchunduru, @dstiliadis or @bvandewalle will reply to your question in the next days!

**Comment by dstiliadis** [comment]
With the latest commits it should work fine. You can try the example with the --remote option and then its completely transparent to the network technology used. Packet capture is happening before the packet exits the container namespace and the host networking mode doesn't matter. We have tried it with several techniques, but not Weave. If you try it with Weave, please report back.
