### ISSUE TITLE
Logs: Received application ACK packet in the wrong state! 2

### ISSUE THREAD

**Issue by bvandewalle** [aporeto-inc/trireme#278]
Looking at the logs, I can find a lot of those:

{"level":"debug","ts":1497986446.561756,"caller":"enforcer/datapath_tcp.go:192","msg":"Dropping packet  ","flow":"10.8.1.19:10.8.1.18:80:59642","Flags":".AP...","error":"Received application ACK packet in the wrong state! 2"}

**Comment by dstiliadis** [comment]
Fixed by PR #310
