### ISSUE TITLE
[REFACTORING] linter is currently deactivated for some unit tests

### ISSUE THREAD

**Issue by Dogild** [aporeto-inc/trireme#385]
Right now, the gometalinter is deactivated for some unittests.

The method deactivated are marked with the following comments :
```golang
// TODO: remove nolint
// nolint
func (p *Packet) AddTCPLayer(srcPort layers.TCPPort, dstPort layers.TCPPort) error {
```
Deactivated methods are in the packages : `packetgen` and `cgnetcls`.
Reactivated the test will probably needs some refactoring

**Comment by sibicramesh** [comment]
Fixed: https://github.com/aporeto-inc/trireme/pull/387
