### ISSUE TITLE
unable to compile the code on rhel7/go1.4.2

### ISSUE THREAD

**Issue by Pavanvk** [aporeto-inc/trireme#81]
# make build
CGO_ENABLED=1 go build -a -installsuffix cgo
/local/golang/src/github.com/docker/docker/client/hijack.go:15:2: no buildable Go source files in /local/golang/src/github.co
make: *** [build] Error 1

code seems not to compile either on 1.5 + due to circular import issues..

**Comment by bvandewalle** [comment]
Hi,

Can you give us a full stack trace ?  Are you trying to build the Example ?
We are testing/building the code against go1.7. 1.6 should work also.
1.4 is definitely not supported and I would have my doubts on 1.5.

**Comment by Pavanvk** [comment]
Hi,

yes am trying to build the example. i tried to build it with 1.7 but didnt work. will post the stack trace in a min

**Comment by Pavanvk** [comment]
here is the error 

example]# make build
CGO_ENABLED=1 go build -a -installsuffix cgo
import cycle not allowed
package github.com/aporeto-inc/trireme/example
        imports flag
        imports errors
        imports runtime
        imports runtime/internal/atomic
        imports unsafe
        imports runtime
import cycle not allowed
package github.com/aporeto-inc/trireme/example
        imports github.com/aporeto-inc/trireme
        imports github.com/aporeto-inc/trireme/enforcer
        imports github.com/aporeto-inc/trireme/collector
        imports github.com/aporeto-inc/trireme/enforcer/packet
        imports golang.org/x/net/ipv4
        imports golang.org/x/net/internal/netreflect
        imports net
        imports runtime/cgo
        imports runtime/cgo
make: *** [build] Error 1
[root@833853vm1 example]# go version
go version go1.7.1 linux/amd64

**Comment by bvandewalle** [comment]
Can you try a 
glide install ; make build ? With go 1.7

**Comment by bvandewalle** [comment]
@Pavanvk: 
I just built Trireme on a brand new Trireme on Centos7 and had no issues. The only hard requirement is to install libnetfilter-queue,and the whole GCC building tools.

```
[centos@ip-172-31-35-164 docker]$ go version
go version go1.7.4 linux/amd64
[centos@ip-172-31-35-164 docker]$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/centos/golang/"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build376119536=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
[centos@ip-172-31-35-164 docker]$ 
```

Could you try again and let us know ? 

```
[centos@ip-172-31-35-164 example]$ make build
CGO_ENABLED=1 go build -a -installsuffix cgo
make package
make[1]: Entering directory `/home/centos/golang/src/github.com/aporeto-inc/trireme/example'
mv example docker/trireme-example
make[1]: Leaving directory `/home/centos/golang/src/github.com/aporeto-inc/trireme/example'
[centos@ip-172-31-35-164 example]$ 
```
