### ISSUE TITLE
trireme-example does not see packets from containers on overlay network and with macvlan interfaces

### ISSUE THREAD

**Issue by Pavanvk** [aporeto-inc/trireme#84]
trireme standalone does not see any packets if a container is on docker overlay network or uses macvlan interfaces.

simple swarm overlay network setup as described in docker documentation can be used to reproduce the issue.

do we need different policy config for correct nfqueue chains? or it agnostic of policy configuration the prerouting chain should see the packet?

**Comment by dstiliadis** [comment]
We have to document this,  Trireme does not support Docker Swarm. We are working to address this. Essentially capturing packets before any of the complexities of the VXLAN.

**Comment by Pavanvk** [comment]
kindly keep me posted. would help in testing if experimental bits are available.

**Comment by dstiliadis** [comment]
This works now by using remote enforcers that implement the policy within the container namespace and don't care about the network implementation.
