### ISSUE TITLE
orchestration agnostic policy definition

### ISSUE THREAD

**Issue by Pavanvk** [aporeto-inc/trireme#96]
Network policy definition should be orchestration agnostic. Though trireme supports k8s policy definition which makes it simpler to define policies. should be usefull to have simpler independent policy definition to support k8s,swarm etc..

**Comment by bvandewalle** [comment]
@Pavanvk : Note that Tirereme policy definition is not tight to Kubernetes and we actually have our own Policy definition model.
I'm in the middle of creating a user document that describes how to use Trireme as a generic Policy definition outside of Trireme, will report back on this issue as soon as it is out there.

**Comment by bvandewalle** [comment]
@Pavanvk : This document explains how to create policy that are "Orchestration agnostic"
https://github.com/aporeto-inc/trireme/blob/master/docs/policy_design.md
